core/urls.py
from django.urls import path
from .views import (index,
        addDonnorInfo, 
        updateDonnorInfo, 
        addPatientInfo, 
        updatePatientInfo, 
        RequestBlood,
        HandleBloodRequest,
        sendDonorRequest,
        donationRequests,
        userDonate,
    )

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),

    path('donr-register', index, name='regdonor'),
    path('add-donor-info', addDonnorInfo.as_view(), name='add-donor-info'),
    path('update-donor-info/<int:pk>', updateDonnorInfo.as_view(), name='update-donor-info'),
    path('add-patient-info', addPatientInfo.as_view(), name='add-patient-info'),
    path('update-patient-info/<int:pk>', updatePatientInfo.as_view(), name='update-patient-info'),
    path('request-blood-donation', RequestBlood.as_view(), name='request-blood-donation'),
    path('my-requests',HandleBloodRequest, name='my-requests'),
    path('send-request/<int:pk>', sendDonorRequest, name='send-request'),
    path('donation-requests', donationRequests.as_view(), name='donation-requests'),
    path('user-donate/<int:pk>', userDonate, name='user-donate'),


]

donornet/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as v
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register', v.register, name='register'),
    path('', include("django.contrib.auth.urls")),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from users.models import User
from django.core.validators import MaxValueValidator , MinValueValidator
from django.core.validators import RegexValidator
from django_countries.fields import CountryField
from django.urls import reverse

# Create your models here.
blood_choices = [
        ('A+ve', 'A+ve'),
        ('A-ve', 'A-ve'),
        ('B+ve', 'B+ve'),
        ('B-ve', 'B-ve'),
        ('AB+ve', 'AB+ve'),
        ('AB-ve', 'AB-ve'),
        ('O+ve', 'O+ve'),
        ('O-ve', 'O-ve'),
        ]

gender_choices = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Others')
]

class Donor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name= models.CharField( max_length=150)
    age = models.IntegerField(validators=[MinValueValidator(17), MaxValueValidator(70)])
    gender = models.CharField(max_length=50, choices=gender_choices)
    phone_number = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])
    location1 = models.CharField( max_length=50)
    location2 = models.CharField( max_length=50, null=True, blank=True)
    country = CountryField(blank_label='(select country)')
    blood_group = models.CharField(max_length=10, choices=blood_choices)  
    verification_document = models.ImageField(upload_to='verification_document', null=False, blank=False, help_text='Upload image of document to verify your blood group.(eg. license, Donation card etc.')
    is_verified = models.BooleanField(default=False)
    # last_donated = models.DateField(null=True, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)

    can_donate = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.full_name} : {self.blood_group}'
    
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name= models.CharField( max_length=150)
    age = models.IntegerField(validators=[MinValueValidator(17), MaxValueValidator(70)])
    gender = models.CharField(max_length=50, choices=gender_choices)
    phone_number = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])
    
    date_joined = models.DateTimeField(default=timezone.now)

    is_donor = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.full_name} '

class BloodRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blood_group = models.CharField(max_length=10, choices=blood_choices)
    phone_number = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])
    country = CountryField(blank_label='(select country)')
    location1 = models.CharField( max_length=50)
    location2 = models.CharField( max_length=50, null=True, blank=True)
    required_on = models.DateTimeField(blank=False, null=False)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:send-request',kwargs={'pk':self.pk})
    
    def __str__(self):
        return f'{self.country}-{self.location1} : {self.blood_group}'


class DonorRequest(models.Model):
    bloodrequest = models.ForeignKey(BloodRequest, on_delete=models.CASCADE)
    user = models.ManyToManyField(User)

    def __Str__(self):
        return f'{self.bloodrequest.blood_group}'


class DonorAccept(models.Model):
    bloodrequest = models.ForeignKey(BloodRequest, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_accepted = models.BooleanField(default=False)

    def __Str__(self):
        return f'{self.bloodrequest.blood_group}'

core/forms.py
from django import forms
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField

class SearchDonorForm(forms.Form):
	blood_choices = [
        ('A+ve', 'A+ve'),
        ('A-ve', 'A-ve'),
        ('B+ve', 'B+ve'),
        ('B-ve', 'B-ve'),
        ('AB+ve', 'AB+ve'),
        ('AB-ve', 'AB-ve'),
        ('O+ve', 'O+ve'),
        ('O-ve', 'O-ve'),
        ]

	country = CountryField(blank_label='select country').formfield()
	blood_group = forms.ChoiceField(required=True, choices=blood_choices)
	location = forms.CharField(required=True, max_length= 50, 
				widget = forms.TextInput(attrs={
					'name':'location',
					'placeholder': 'Enter location eg: Kathmandu'
					}) )

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView
from django.db.models import Q
from .models import Donor, Patient, BloodRequest, DonorRequest, DonorAccept
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import SearchDonorForm
from .send_sms import welcome_message, send_donation_request,send_donoraccept_request
from django.contrib.auth.decorators import login_required

def index(request):
	if request.method == 'POST':
		r_country = request.POST['country']
		r_blood_group = request.POST['blood_group']
		r_location = request.POST['location']


		country_donor_records = Donor.objects.filter(country=r_country)
		country_donor_records_total = country_donor_records.count()
		location_donor_records = country_donor_records.filter(Q(location1=r_location) | Q(location2=r_location))
		location_donor_records_total = location_donor_records.count()
		bloodgroup_donor_records = location_donor_records.filter(blood_group=r_blood_group)
		bloodgroup_donor_records_total = bloodgroup_donor_records.count()

		context = {
			'r_country' : r_country,
			'r_location' : r_location,
			'r_blood_group' : r_blood_group,
			'country_donor_records_total' : country_donor_records_total,
			'location_donor_records_total' : location_donor_records_total,
			'bloodgroup_donor_records_total' : bloodgroup_donor_records_total
		}

		return render(request, 'core/donorsearchresult.html', context)

	else:
		form = SearchDonorForm
	return render(request, 'core/index.html', {'form': form})


class addDonnorInfo(LoginRequiredMixin, UserPassesTestMixin, CreateView):

	

	model = Donor
	fields = ['full_name','age', 'gender', 'phone_number', 'blood_group', 'country', 'location1', 'location2','verification_document']
	template_name = 'core/createdonorprofile.html'
	success_url = reverse_lazy('core:index')


	# def get_form(self):
	# 	'''add date picker in forms'''
	# 	from django.forms.widgets import SelectDateWidget
	# 	form = super(addDonnorInfo, self).get_form()
	# 	form.fields['last_donated'].widget = SelectDateWidget(years=range(2019, 2021))
		
	# 	return form
		
	def form_valid(self, form):
		form.instance.user = self.request.user
		r_phone = form.cleaned_data['phone_number']
		r_name = form.cleaned_data['full_name']
		welcome_message(r_phone, r_name)
		return super().form_valid(form)


	def test_func(self):

		check_user_info = Donor.objects.filter(user=self.request.user)			
		if not check_user_info:
			return True
		return False

	def user_passes_test(self, request):
		if request.user.is_authenticated:
			check_user_info = Donor.objects.filter(user=self.request.user)

			if not check_user_info:
				return True
			return False

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			if not self.user_passes_test(request):
				user_profile = Donor.objects.filter(user=self.request.user)
				return redirect('core:update-donor-info', pk=user_profile[0].pk)
		return super(addDonnorInfo, self).dispatch(
		    request, *args, **kwargs)


class updateDonnorInfo(LoginRequiredMixin, UpdateView):
	model = Donor
	fields = ['full_name','age', 'gender', 'phone_number', 'blood_group', 'country', 'location1', 'location2', 'can_donate','verification_document']
	template_name = 'core/updatedonorinfo.html'
	success_url = reverse_lazy('core:index')

	

	def user_passes_test(self, request):
		if request.user.is_authenticated:
		    self.object = self.get_object()
		    return self.object.user == request.user
		return False

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			user_profile = Donor.objects.filter(user=self.request.user)
			
			if not self.user_passes_test(request):
				if not user_profile:
					return redirect('core:add-donor-info')
				return redirect('core:update-donor-info', pk=user_profile[0].pk)
		return super(updateDonnorInfo, self).dispatch(
	    request, *args, **kwargs)


class addPatientInfo(LoginRequiredMixin, UserPassesTestMixin, CreateView):

	

	model = Patient
	fields = ['full_name','age', 'gender', 'phone_number']
	template_name = 'core/addpatientinfo.html'
	success_url = reverse_lazy('core:index')


		
	def form_valid(self, form):
		form.instance.user = self.request.user
		r_phone = form.cleaned_data['phone_number']
		r_name = form.cleaned_data['full_name']
		welcome_message(r_phone, r_name)
		return super().form_valid(form)


	def test_func(self):

		check_user_info = Patient.objects.filter(user=self.request.user)			
		if not check_user_info:
			return True
		return False

	def user_passes_test(self, request):
		if request.user.is_authenticated:
			check_user_info = Patient.objects.filter(user=self.request.user)

			if not check_user_info:
				return True
			return False

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			if not self.user_passes_test(request):
				user_profile = Patient.objects.filter(user=self.request.user)
				return redirect('core:update-patient-info', pk=user_profile[0].pk)
		return super(addPatientInfo, self).dispatch(
		    request, *args, **kwargs)

class updatePatientInfo(LoginRequiredMixin, UpdateView):
	model = Patient
	fields = ['full_name','age', 'gender', 'phone_number']
	template_name = 'core/updatepatientinfo.html'
	success_url = reverse_lazy('core:index')

	

	def user_passes_test(self, request):
		if request.user.is_authenticated:
		    self.object = self.get_object()
		    return self.object.user == request.user
		return False

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			user_profile = Patient.objects.filter(user=self.request.user)
			
			if not self.user_passes_test(request):
				if not user_profile:
					return redirect('core:add-patient-info')
				return redirect('core:update-patient-info', pk=user_profile[0].pk)
		return super(updatePatientInfo, self).dispatch(
	    request, *args, **kwargs)


class RequestBlood(LoginRequiredMixin, CreateView):
	model = BloodRequest
	fields = ['blood_group', 'phone_number', 'country', 'location1', 'location2', 'required_on']
	template_name = 'core/requestblood.html'

	def get_form(self):
		'''add date picker in forms'''
		from django.forms.widgets import SelectDateWidget
		form = super(RequestBlood, self).get_form()
		form.fields['required_on'].widget = SelectDateWidget()
		
		return form

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)



@login_required
def HandleBloodRequest(request):
	user = request.user

	user_blood_request = BloodRequest.objects.filter(user=user)
	context={
		'user_blood_request' : user_blood_request,
	}
	
	return render(request, 'core/userbloodrequest.html', context)


@login_required
def sendDonorRequest(request, pk):
	user = request.user
	request_data = BloodRequest.objects.get(pk=pk)
	accepted_donors = []
	ready_donor_data = DonorAccept.objects.filter(bloodrequest=request_data)
	for donor in ready_donor_data:
		donor_data = Donor.objects.get(user=donor.user)
		accepted_donor_data = {
			'full_name' : donor_data.full_name,
			'country' : donor_data.country,
			'location1' : donor_data.location1,
			'location2' : donor_data.location2,
			'blood_group' : donor_data.blood_group,
			'phone_number': donor_data.phone_number,


		}

		accepted_donors.append(accepted_donor_data)
	

	if request_data.user == user:
		current_user_request = True
	else:
		current_user_request = False

	current_user_is_donor_check = DonorAccept.objects.filter(user=request.user)
	if not current_user_is_donor_check:
		current_user_is_donor = False
	else:
		current_user_is_donor = True


	req_bloodgroup = request_data.blood_group
	req_country = request_data.country
	req_location1 = request_data.location1
	req_location2 = request_data.location2
	req_required_on = request_data.required_on

	country_donor_records = Donor.objects.filter(country=req_country)
	country_donor_records_total = country_donor_records.count()
	location_donor_records = country_donor_records.filter(Q(location1=req_location1) | Q(location2=req_location2))
	location_donor_records_total = location_donor_records.count()
	matching_records = location_donor_records.filter(blood_group=req_bloodgroup)[:10]
	matching_records_total = matching_records.count()

	request_check = DonorRequest.objects.filter(bloodrequest=request_data)

	if not request_check:
	
		instance = DonorRequest.objects.create(bloodrequest=request_data)
		for record in matching_records:
			send_donation_request(record.phone_number, record.full_name, req_country, req_location1, req_bloodgroup, pk)
			instance.user.add(record.user)



	context = {
			'req_country' : req_country,
			'req_location' : req_location1,
			'req_blood_group' : req_bloodgroup,
			'req_required_on' : req_required_on,
			'country_donor_records_total' : country_donor_records_total,
			'location_donor_records_total' : location_donor_records_total,
			'matching_records_total' : matching_records_total,
			'current_user_request' : current_user_request,
			'accepted_donors' : accepted_donors,
			'bloodrequest_pk' : pk,
			'current_user_is_donor' : current_user_is_donor,
		}
	
	return render(request, 'core/myrequestdata.html', context)


class donationRequests(ListView):
	queryset = BloodRequest.objects.filter(is_active=True).order_by('-date_created')
	template_name = 'core/donationrequests.html'
	paginate_by = 12
	context_object_name = 'donation_requests'


@login_required
def userDonate(request, pk):
	user = request.user
	request_data = BloodRequest.objects.get(pk=pk)

	check_if_donor = Donor.objects.filter(user = user)
	request_check = DonorAccept.objects.filter(bloodrequest=request_data).filter(user=user)
	
	if check_if_donor or request_data.user == user:
		if request_data.user == user:
			return redirect('core:send-request', pk=pk)
		else:

core/templates/core/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}">



    <title>Save Life</title>
  </head>
  <body>

    
<nav class="navbar navbar-expand-lg navbar-light">
  <a href="/" class="navbar-brand"><img src="{% static 'core/images/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <em style="color: purple; font-size: 30px;"> BloodFinder </em></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar2">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbar2">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">Home</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:index' %}#search">Search Donors</a>
                
            </li>
            <li class="nav-item">

                <a class="nav-link" href="{% url 'core:donation-requests' %}">Blood Requests</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:request-blood-donation' %}"><p>Request Blood</p></a>
            </li>
            
        </ul>

        <ul class="navbar-nav ">
          {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}"><p>Log Out</p></a>
            </li>
           
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><p>Log In</p></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}"><p>Register</p></a>
            </li>
          {% endif %}

    </ul>
    </div>
</nav>

     
  



        {% block content %}
        {% endblock %}


  <footer id="sticky-footer">
    <div class="container ">
      <div class="row">
        <div class="col-sm">
          <img class="footer_logo" src="{% static 'core/images/logo.png' %}"> 
           <em style="color: white; font-size: 30px;"> Blood Bank </em> <br><br>
           <img class=" social_icons" src="{% static 'core/images/fb.png' %}">
           <img class=" social_icons" src="{% static 'core/images/insta.png' %}">
           <img class=" social_icons" src="{% static 'core/images/twtr.png' %}"> <br><br>
         
        </div>
        <div class="col-sm">
          <h3 class="footer_info">Our Organization</h3>
          <h5 class="footer_info"> History</h4>
          <h5 class="footer_info"> Location</h4>
          <h5 class="footer_info"> Working Hours</h4>
        </div>
        <div class="col-sm">
           <h3 class="footer_info">Resources</h3>
          <h5 class="footer_info"> FAQa</h4>
          <h5 class="footer_info"> Donor form</h4>
          <h5 class="footer_info"> Questionnaire</h4>
          <h5 class="footer_info"> Contact US</h4>
        </div>
      </div>

      <div class="copyright">

        © 2019 Blood Bank. All Rights Reserved. 
        
      </div>

    </div>
  </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/donationrequests.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
		
		<h4 class="card-title mt-2 text-center">Blood Donation Request</h4>

	<div style="margin-left: 20%; margin-right: 20%; text-align: center">
		{% if messages %}
       		{% for message in messages %}

     			<div class="alert alert-{{ message.tags }}">
         			{{ message }}
				</div>

         	{% endfor %}
        {% endif %}
	</div>
		
		<div class="container">
			{% if donation_requests %}
			<div class="row">
				{% for donation_request in donation_requests %}
				<div class="col-lg-4 col-md-6">
			

				<div class="search_card card " style="max-width: 500px;">
				<article class="card-body mx-auto" style="max-width: 400px;">
					

					<h2 class="blood_group_card"> {{ donation_request.blood_group }} </h2>
					<br>

					<p class="user_blood_request_info">
						Country: {{ donation_request.country }} <br>
						Location: {{ donation_request.location1 }} 
						{% if donation_request.location2 %}
							, {{ donation_request.location2 }}
						{% endif %}
						<br>
						
						Required On : {{ donation_request.required_on }}
						<br><br>
						{% if donation_request.user.email == request.user.email  %}
							<a href="{% url 'core:user-donate' donation_request.pk %}"><button type="btn" class="btn-primary">View</button></a>
						{% else %}
							<a href="{% url 'core:user-donate' donation_request.pk %}"><button type="btn" class="btn-primary">Donate</button></a>
						{% endif %}
						
					
					</p>
				</article>
				</div> <!-- card.// -->

			</div>
			{% endfor %}




		</div>
		
		{% endif %}
		{% if is_paginated %}
  <nav aria-label="Page navigation conatiner"></nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
  </ul>
  </nav>
</div>
{% endif %}
	</div>
				<!--container end.//-->









{% endblock %}

core/templates/core/donorsearchresult.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

		
		<div class="container">

			
			

			<div class="search_card card " style="max-width: 500px;">
				<article class="card-body mx-auto" style="max-width: 400px;">
					<h4 class="card-title mt-2 text-center">Search Results</h4>

					There are {{ bloodgroup_donor_records_total }} donors in {{ r_location }}, {{ r_country }} that matches your query. <br>
					<small>Query:(country: {{ r_country }}, location: {{ r_location }}, Blood group: {{ r_blood_group }}) </small>
					<br><br>

					{% if bloodgroup_donor_records_total >= 1 %}

						<a href="{% url 'core:request-blood-donation' %}"><button type="btn" class="btn-primary">Request Blood Donation</button></a>
					{%  else %}
						<p>You can search for donors in nearby city or use a general location.</p> 
						There are {{ country_donor_records_total }} donors registered in {{ r_country }}. <br><br>
						<a href="{% url 'core:index' %}"><button type="btn" class="btn-primary">Search Donors</button> </a>
					{% endif %}

					<br> <br><br>
					{% if not user.is_authenticated %}
						<a href="{% url 'register' %}">Donate Blood. save Life</a>
					
					{% endif %}
					
				</article>
				</div> <!-- card.// -->

				</div> 
				<!--container end.//-->









{% endblock %}

core/templates/core/myrequestdata.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
	
	<div style="margin-left: 20%; margin-right: 20%; text-align: center">
		{% if messages %}
       		{% for message in messages %}

     			<div class="alert alert-{{ message.tags }}">
         			{{ message }}
				</div>

         	{% endfor %}
        {% endif %}
	</div>

	{% if current_user_request == True %}
		
		<div class="container">
			
			<div class="row">

				
				<div class="col-lg-5 col-md-4">
			

				<div class="search_card card " style="max-width: 500px;">
				<article class="card-body mx-auto" style="max-width: 400px;">
					

					<h2 class="blood_group_card"> Donation Request </h2>
					<br>

					There are {{ matching_records_total }} donors in {{ req_location }}, {{ req_country }} that matches your query. <br>
					<small>Query:(country: {{ req_country }}, location: {{ req_location }}, Blood group: {{ req_blood_group }}) </small>
					<br><br>

					{% if matching_records_total <= 0 %}
						<h4>Sorry!! We could not find any donors matching your query.</h4>
						<h6><em> Try searching for general location. You can search for nearby cities if that is feasible. <br>
						Some information that may help:
						There are {{ country_donor_records_total }} donors in {{ req_country }} and {{ location_donor_records_total }} donors in {{ req_location }}
						</em>
						</h6>
					{% elif matching_records_total < 15 %}
						<h4>We have sent sms request to {{ matching_records_total }} donors that matches your query. Please wait for their response.</h4>
					{% elif matching_records_total >= 15 %}
						<h4>We have sent sms request to 15 donors that matches your query. Please wait for their response.</h4>

						</h4>

					{% endif %}

						
						
					
					</p>
				</article>
				</div> <!-- card.// -->

			</div>

			<div class="col-lg-7 col-md-8">
			

				<div class="search_card card " style="max-width: 500px;">
				<article class="card-body mx-auto" style="max-width: 400px;">
					{% if accepted_donors %}

					<h2 class="blood_group_card"> Donors Ready to help </h2>
					<br>
					

					{% for donor in accepted_donors %}

						<h4>{{ donor.full_name }} </h4>
						Country:{{ donor.country }}<br>
						Location: {{ donor.location1 }}
						{% if location2 %} , {{ donor.location2 }} {% endif %}<br>
						Blood group: {{ donor.blood_group }}<br>
						Phone: {{ donor.phone_number }}
						<br>
						
						<hr color=black>
					
					{% endfor %}

					{% else %}
					

					

				
					<small>Query:(country: {{ req_country }}, location: {{ req_location }}, Blood group: {{ req_blood_group }}) </small>
					<br><br>

					<h4>Here you will see donors who want to donate and you can accept donation.</h4>
					

						
						
					
				{% endif %}
				</article>
				</div> <!-- card.// -->

			</div>
			
		</div>
		


		
	</div>

				<!--container end.//-->



	{% else %}


		<div class="container">
			
			<div class="row">

				
				<div class="col-lg col-md">
			

				<div class="search_card card " style="max-width: 500px;">
				<article class="card-body mx-auto" style="max-width: 400px;">
					

					<h2 class="blood_group_card"> {{ req_blood_group }} </h2>
					<br>

					<p class="user_blood_request_info">
						Country: {{ req_country }} <br>
						Location: {{ req_location }} 
						<br>
						Required On : {{ req_required_on }}
						<br><br>

						{% if current_user_is_donor == True %}

						<button type="btn" class="btn-primary disabled">You are willing to donate.</button>

						{% else %}
						<a href="{% url 'core:user-donate' bloodrequest_pk %}"><button type="btn" class="btn-primary">Donate</button></a>

						{% endif %}

						
					
					</p>
				</article>
				</div> <!-- card.// -->

			</div>
			
		</div>
		


		
	</div>




	{% endif %}





{% endblock %}